Title: Vytautas Stasiunaitis
logo: assets/img/free_small.jpg
description: the surgeon that fell in love with the code. Highly passionate about technological and scientific progress.
theme: jekyll-theme-minimal
